export const GET_COURSE_STARTING = 'GET_COURSE_STARTING';
export const GET_COURSES = 'GET_COURSES';
export const GET_COURSE_ERROR = 'GET_COURSE_ERROR';

export const ADD_COURSE_STARTING = 'ADD_COURSE_STARTING';
export const ADD_COURSES = 'ADD_COURSES';
export const ADD_COURSE_ERROR = 'ADD_COURSE_ERROR';

export const UPDATE_COURSE_STARTING = 'UPDATE_COURSE_STARTING';
export const UPDATE_COURSES = 'UPDATE_COURSES';
export const UPDATE_COURSE_ERROR = 'UPDATE_COURSE_ERROR';

export const DELETE_COURSE_STARTING = 'DELETE_COURSE_STARTING';
export const DELETE_COURSES = 'DELETE_COURSES';
export const DELETE_COURSE_ERROR = 'DELETE_COURSE_ERROR';