export const GET_COURSE_STARTING = 'GET_COURSE_STARTING';
export const GET_COURSES = 'GET_COURSES';
export const GET_COURSE_ERROR = 'GET_COURSE_ERROR';

export const ADD_COURSE_STARTING = 'ADD_COURSE_STARTING';
export const ADD_COURSE = 'ADD_COURSE';
export const ADD_COURSE_ERROR = 'ADD_COURSE_ERROR';

export const UPDATE_COURSE_STARTING = 'UPDATE_COURSE_STARTING';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_COURSE_ERROR = 'UPDATE_COURSE_ERROR';

export const DELETE_COURSE_STARTING = 'DELETE_COURSE_STARTING';
export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_COURSE_ERROR = 'DELETE_COURSE_ERROR';