export const GET_COURSE_STARTING = 'GET_COURSE_STARTING';
export const GET_COURSES = 'GET_COURSES';
export const GET_COURSE_ERROR = 'GET_COURSE_ERROR';

export const ADD_COURSE_STARTING = 'ADD_COURSE_STARTING';
export const ADD_COURSE = 'ADD_COURSE';
export const ADD_COURSE_ERROR = 'ADD_COURSE_ERROR';

export const UPDATE_COURSE_STARTING = 'UPDATE_COURSE_STARTING';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const UPDATE_COURSE_ERROR = 'UPDATE_COURSE_ERROR';

export const DELETE_COURSE_STARTING = 'DELETE_COURSE_STARTING';
export const DELETE_COURSE = 'DELETE_COURSE';
export const DELETE_COURSE_ERROR = 'DELETE_COURSE_ERROR';

export const GET_MEDIA_STARTING = 'GET_MEDIA_STARTING';
export const GET_MEDIA = 'GET_MEDIA';
export const GET_MEDIA_ERROR = 'GET_MEDIA_ERROR';

export const ADD_MEDIA_STARTING = 'ADD_MEDIA_STARTING';
export const ADD_MEDIA = 'ADD_MEDIA';
export const ADD_MEDIA_ERROR = 'ADD_MEDIA_ERROR';

export const UPDATE_MEDIA_STARTING = 'UPDATE_MEDIA_STARTING';
export const UPDATE_MEDIA = 'UPDATE_MEDIA';
export const UPDATE_MEDIA_ERROR = 'UPDATE_MEDIA_ERROR';

export const DELETE_MEDIA_STARTING = 'DELETE_MEDIA_STARTING';
export const DELETE_MEDIA = 'DELETE_MEDIA';
export const DELETE_MEDIA_ERROR = 'DELETE_MEDIA_ERROR';

export const GET_USERS_STARTING = 'GET_USERS_STARTING';
export const GET_USERS = 'GET_USERS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const ADD_USER_STARTING = 'ADD_USER_STARTING';
export const ADD_USER = 'ADD_USER';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const UPDATE_USER_STARTING = 'UPDATE_USER_STARTING';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DELETE_USER_STARTING = 'DELETE_USER_STARTING';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';